- hosts: localhost
  gather_facts: false
  # vars_files:
  #    - vars.yml
  become: True
  tasks:    
      - name: Install python3 & git package
        yum:
          pkg:
            - python3
            - git
          state: installed

      - name: Clone github repository
        git:
         repo: 'https://github.com/anikpujan/Python-Demo.git'
         dest: /home/ec2-user/Python_Scraping_project
         update: no

      - name: Install requests & beautifulsoup using pip3
        pip:
          name:
            - requests
            - beautifulsoup4
          executable: pip3

      - name: Run the script command
        become: true
        shell: python3 /home/ec2-user/Python_Scraping_project/weather.py

  
  
 
      - name: Install Python 
        yum:
         name: python3-pip
         state: present
      - name: Ensure boto and boto3 modules are installed
        pip:
         name: 
          - boto
          - boto3
          - botocore
         executable: pip3
      - name: Create Bucket
        aws_s3:
          bucket: aniks 
          mode: create
          permission: public-read-write
      - name: Put CSV file in the bucket
        aws_s3:
           bucket: aniks
           object: weather.csv
           src: /home/ec2-user/Python_Scraping_project/weather.csv
           mode: put
           permission: public-read-write

      - name: Get the CSV file
        aws_s3:
           bucket: aniks
           object: weather.csv
           dest: /home/ec2-user/CSV/weather.csv
           mode: get         
      
